export default [
	{
	  topicName: "Array",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Set Matrix Zeros",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/set-matrix-zeroes/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Pascal Triangle",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/pascals-triangle/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Next Permutation",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/next-permutation/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Kadane’s Algorithm",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/maximum-subarray/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Sort an array of 0's 1's 2's",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/sort-colors/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		}, 
		{
		  Problem: "Stock Buy and Sell",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Rotate Matrix",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/rotate-image/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Merge Overlapping Subintervals",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/merge-intervals/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Merge two sorted Arrays without extra space",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/merge-sorted-array/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find the duplicate in an array of N+1 integers.",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/find-the-duplicate-number/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Repeat and Missing Number",
		  Topic: "Array",
		  URL: "https://www.interviewbit.com/problems/repeat-and-missing-number-array/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Inversion of Array",
		  Topic: "Array",
		  URL: "https://www.codingninjas.com/codestudio/problems/count-inversions_615",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Search in a 2d Matrix",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/search-a-2d-matrix/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		}, 
		{
		  Problem: "Pow(X,n)",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/powx-n/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		}, 
		{
		  Problem: "Majority Element (>N/2 times)",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/majority-element/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		}, 
		{
		  Problem: "Majority Element (>N/3 times)",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/majority-element-ii/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		}, 
		{
		  Problem: "Grid Unique Paths",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/unique-paths/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		}, 
		{
		  Problem: "Reverse Pairs",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/reverse-pairs/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "2-Sum-Problem",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/two-sum/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "4-sum-Problem",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/4sum/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Longest Consecutive Sequence",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/longest-consecutive-sequence/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Largest Subarray with 0 sum",
		  Topic: "Array",
		  URL: "https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Count number of subarrays with given Xor K",
		  Topic: "Array",
		  URL: "https://www.interviewbit.com/problems/subarray-with-given-xor/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Longest Substring without repeat",
		  Topic: "Array",
		  URL: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		}, 
	   ]
	  },
	  {
	  topicName: "Linked List",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Reverse a LinkedList",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/reverse-linked-list/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find the middle of LinkedList",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/middle-of-the-linked-list/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Merge two sorted Linked List",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/merge-two-sorted-lists/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Remove N-th node from back of LinkedList",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Add two numbers as LinkedList",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/add-two-numbers/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Delete a given Node when a node is given.",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/delete-node-in-a-linked-list/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find intersection point of Y LinkedList",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/intersection-of-two-linked-lists/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Detect a cycle in Linked List",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/linked-list-cycle/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Reverse a LinkedList in groups of size k",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Check if a LinkedList is palindrome or not",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/palindrome-linked-list/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find the starting point of the Loop of LinkedList",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/linked-list-cycle-ii/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Flattening of a LinkedList",
		  Topic: "LinkedList",
		  URL: "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Rotate a LinkedList",
		  Topic: "LinkedList",
		  URL: "https://leetcode.com/problems/rotate-list/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "Greedy",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "N meeting in one room",
		  Topic: "Greedy",
		  URL: "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Minimum number of platforms required for a railway",
		  Topic: "Greedy",
		  URL: "https://practice.geeksforgeeks.org/problems/minimum-platforms-1587115620/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Job sequencing Problem",
		  Topic: "Greedy",
		  URL: "https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Fractional Knapsack Problem",
		  Topic: "Greedy",
		  URL: "https://practice.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Greedy algorithm to find minimum number of coins",
		  Topic: "Greedy",
		  URL: "https://practice.geeksforgeeks.org/problems/number-of-coins1824/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Activity Selection",
		  Topic: "Greedy",
		  URL: "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "Recursion",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Subset Sums",
		  Topic: "Recursion",
		  URL: "https://practice.geeksforgeeks.org/problems/subset-sums2234/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Subset-II",
		  Topic: "Recursion",
		  URL: "https://leetcode.com/problems/subsets-ii/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Combination sum-1",
		  Topic: "Recursion",
		  URL: "https://leetcode.com/problems/combination-sum/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Combination sum-2",
		  Topic: "Recursion",
		  URL: "https://leetcode.com/problems/combination-sum-ii/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Palindrome Partitioning",
		  Topic: "Recursion",
		  URL: "https://leetcode.com/problems/palindrome-partitioning/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "K-th permutation Sequence",
		  Topic: "Recursion",
		  URL: "https://leetcode.com/problems/permutation-sequence/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "Recursion & Backtracking",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Print all permutations of a string/array",
		  Topic: "Recursion & Backtracking",
		  URL: "https://leetcode.com/problems/permutations/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "N queens Problem",
		  Topic: "Recursion & Backtracking",
		  URL: "https://leetcode.com/problems/n-queens/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Sudoku Solver",
		  Topic: "Recursion & Backtracking",
		  URL: "https://leetcode.com/problems/sudoku-solver/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "M coloring Problem",
		  Topic: "Recursion & Backtracking",
		  URL: "https://practice.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1#",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Rat in a Maze",
		  Topic: "Recursion & Backtracking",
		  URL: "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Word Break",
		  Topic: "Recursion & Backtracking",
		  URL: "https://practice.geeksforgeeks.org/problems/word-break-part-23249/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "Binary Search",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "The N-th root of an integer",
		  Topic: "Binary Search",
		  URL: "https://practice.geeksforgeeks.org/problems/find-nth-root-of-m5843/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Matrix Median",
		  Topic: "Binary Search",
		  URL: "https://www.interviewbit.com/problems/matrix-median/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find the element that appears once in a sorted array, and the rest element appears twice",
		  Topic: "Binary Search",
		  URL: "https://leetcode.com/problems/single-element-in-a-sorted-array/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Search element in a sorted and rotated array/ find pivot where it is rotated",
		  Topic: "Binary Search",
		  URL: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Median of 2 sorted arrays",
		  Topic: "Binary Search",
		  URL: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "K-th element of two sorted arrays",
		  Topic: "Binary Search",
		  URL: "https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Allocate Minimum Number of Pages",
		  Topic: "Binary Search",
		  URL: "https://www.interviewbit.com/problems/allocate-books/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Aggressive Cows",
		  Topic: "Binary Search",
		  URL: "https://www.spoj.com/problems/AGGRCOW/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "TRIES",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Implement Trie (Prefix Tree)",
		  Topic: "TRIES",
		  URL: "https://leetcode.com/problems/implement-trie-prefix-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Implement Trie – 2 (Prefix Tree)",
		  Topic: "TRIES",
		  URL: "https://www.codingninjas.com/codestudio/problems/implement-trie_1387095?utm_source=youtube&utm_medium=affiliate&utm_campaign=striver_tries_videos",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Longest String with All Prefixes",
		  Topic: "TRIES",
		  URL: "https://www.codingninjas.com/codestudio/problems/complete-string_2687860?utm_source=youtube&utm_medium=affiliate&utm_campaign=striver_tries_videos",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Number of Distinct Substrings in a String",
		  Topic: "TRIES",
		  URL: "https://www.codingninjas.com/codestudio/problems/count-distinct-substrings_985292?utm_source=youtube&utm_medium=affiliate&utm_campaign=striver_tries_videos",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Power Set",
		  Topic: "TRIES",
		  URL: "https://practice.geeksforgeeks.org/problems/power-set4302/1#",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Maximum XOR of two numbers in an array",
		  Topic: "TRIES",
		  URL: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Maximum XOR With an Element From Array",
		  Topic: "TRIES",
		  URL: "https://leetcode.com/problems/maximum-xor-with-an-element-from-array/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "Stack and Queue",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Implement Stack Using Arrays",
		  Topic: "Stack and Queue",
		  URL: "https://practice.geeksforgeeks.org/problems/implement-stack-using-array/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Implement Queue Using Arrays",
		  Topic: "Stack and Queue",
		  URL: "https://www.geeksforgeeks.org/array-implementation-of-queue-simple/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Implement Stack using Queue",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/implement-stack-using-queues/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Implement Queue using Stack (O(1) amortized method)",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/implement-queue-using-stacks/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Check for balanced parentheses",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/valid-parentheses/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Next Greater Element",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/next-greater-element-i/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Sort a Stack",
		  Topic: "Stack and Queue",
		  URL: "https://practice.geeksforgeeks.org/problems/sort-a-stack/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Next Smaller Element",
		  Topic: "Stack and Queue",
		  URL: "https://www.interviewbit.com/problems/nearest-smaller-element/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "LRU cache",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/lru-cache/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "LFU Cache",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/lfu-cache/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Largest rectangle in a histogram",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Sliding Window maximum",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/sliding-window-maximum/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Implement Min Stack",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/min-stack/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Rotten Orange",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/rotting-oranges/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Stock Span Problem",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/online-stock-span/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find the maximum of minimums of every window size",
		  Topic: "Stack and Queue",
		  URL: "https://practice.geeksforgeeks.org/problems/maximum-of-minimum-for-every-window-size3453/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "The Celebrity Problem",
		  Topic: "Stack and Queue",
		  URL: "https://leetcode.com/problems/find-the-celebrity/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "String",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Reverse Words in a String",
		  Topic: "String",
		  URL: "https://leetcode.com/problems/reverse-words-in-a-string/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Longest Palindrome in a string",
		  Topic: "String",
		  URL: "https://leetcode.com/problems/longest-palindromic-substring/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Roman Number to Integer and vice versa",
		  Topic: "String",
		  URL: "https://leetcode.com/problems/roman-to-integer/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Implement ATOI/STRSTR",
		  Topic: "String",
		  URL: "https://leetcode.com/problems/string-to-integer-atoi/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Longest Common Prefix",
		  Topic: "String",
		  URL: "https://leetcode.com/problems/longest-common-prefix/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Rabin Karp",
		  Topic: "String",
		  URL: "https://leetcode.com/problems/repeated-string-match/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Z-Function",
		  Topic: "String",
		  URL: "https://leetcode.com/problems/implement-strstr/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "KMP algo / LPS(pi) array",
		  Topic: "String",
		  URL: "https://practice.geeksforgeeks.org/problems/longest-prefix-suffix2527/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Minimum characters needed to be inserted in the beginning to make it palindromic",
		  Topic: "String",
		  URL: "https://www.interviewbit.com/problems/minimum-characters-required-to-make-a-string-palindromic/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Check for Anagrams",
		  Topic: "String",
		  URL: "https://leetcode.com/problems/valid-anagram/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Count and Say",
		  Topic: "String",
		  URL: "https://leetcode.com/problems/count-and-say/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Compare version numbers",
		  Topic: "String",
		  URL: "https://leetcode.com/problems/compare-version-numbers/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "Binary Tree",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Inorder Traversal",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/binary-tree-inorder-traversal/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Preorder Traversal",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/binary-tree-preorder-traversal/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Postorder Traversal",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/binary-tree-postorder-traversal/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "LeftView Of Binary Tree",
		  Topic: "Binary Tree",
		  URL: "https://practice.geeksforgeeks.org/problems/left-view-of-binary-tree/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Bottom View of Binary Tree",
		  Topic: "Binary Tree",
		  URL: "https://practice.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Top View of Binary Tree",
		  Topic: "Binary Tree",
		  URL: "https://practice.geeksforgeeks.org/problems/top-view-of-binary-tree/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Preorder inorder postorder in a single traversal",
		  Topic: "Binary Tree",
		  URL: "https://www.geeksforgeeks.org/preorder-postorder-and-inorder-traversal-of-a-binary-tree-using-a-single-stack/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Vertical order traversal",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Root to node path in a Binary Tree",
		  Topic: "Binary Tree",
		  URL: "https://practice.geeksforgeeks.org/problems/root-to-leaf-paths/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Level order Traversal",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Height of a Binary Tree",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Diameter of Binary Tree",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/diameter-of-binary-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Check if the Binary tree is height-balanced or not",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/balanced-binary-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "LCA in Binary Tree",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Check if two trees are identical or not",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/same-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Zig Zag Traversal of Binary Tree",
		  Topic: "Binary Tree",
		  URL: "https://practice.geeksforgeeks.org/problems/zigzag-tree-traversal/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Boundary Traversal of Binary Tree",
		  Topic: "Binary Tree",
		  URL: "https://practice.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Maximum path sum",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Construct Binary Tree from inorder and preorder",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Construct Binary Tree from Inorder and Postorder",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Symmetric Binary Tree",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/symmetric-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Flatten Binary Tree to LinkedList",
		  Topic: "Binary Tree",
		  URL: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Check if Binary Tree is the mirror of itself or not",
		  Topic: "Binary Tree",
		  URL: "https://practice.geeksforgeeks.org/problems/mirror-tree/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "Binary Search Tree",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Populate Next Right pointers of Tree",
		  Topic: "Binary Search Tree",
		  URL: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Search given Key in BST",
		  Topic: "Binary Search Tree",
		  URL: "https://leetcode.com/problems/search-in-a-binary-search-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Construct BST from given keys",
		  Topic: "Binary Search Tree",
		  URL: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Check is a BT is BST or not",
		  Topic: "Binary Search Tree",
		  URL: "https://leetcode.com/problems/validate-binary-search-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find LCA of two nodes in BST",
		  Topic: "Binary Search Tree",
		  URL: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find the inorder predecessor/successor of a given Key in BST",
		  Topic: "Binary Search Tree",
		  URL: "https://practice.geeksforgeeks.org/problems/predecessor-and-successor/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Floor in a BST",
		  Topic: "Binary Search Tree",
		  URL: "",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Ceil in a BST",
		  Topic: "Binary Search Tree",
		  URL: "",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find K-th smallest element in BST",
		  Topic: "Binary Search Tree",
		  URL: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find K-th largest element in BST",
		  Topic: "Binary Search Tree",
		  URL: "https://practice.geeksforgeeks.org/problems/kth-largest-element-in-bst/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find a pair with a given sum in BST",
		  Topic: "Binary Search Tree",
		  URL: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "BST iterator",
		  Topic: "Binary Search Tree",
		  URL: "https://leetcode.com/problems/binary-search-tree-iterator/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Size of the largest BST in a Binary Tree",
		  Topic: "Binary Search Tree",
		  URL: "https://leetcode.com/problems/maximum-sum-bst-in-binary-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Serialize and deserialize Binary Tree",
		  Topic: "Binary Search Tree",
		  URL: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "Trees Miscellaneous",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Binary Tree to Double Linked List",
		  Topic: "Trees Miscellaneous",
		  URL: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Find median in a stream of running integers",
		  Topic: "Trees Miscellaneous",
		  URL: "https://leetcode.com/problems/find-median-from-data-stream/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "K-th largest element in a stream",
		  Topic: "Trees Miscellaneous",
		  URL: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Distinct numbers in Window",
		  Topic: "Trees Miscellaneous",
		  URL: "https://www.interviewbit.com/problems/distinct-numbers-in-window/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "K-th largest element in an unsorted array",
		  Topic: "Trees Miscellaneous",
		  URL: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Flood-fill Algorithm ",
		  Topic: "Trees Miscellaneous",
		  URL: "https://leetcode.com/problems/flood-fill/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "Graphs",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Clone a graph",
		  Topic: "Graphs",
		  URL: "https://leetcode.com/problems/clone-graph/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "DFS",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/depth-first-traversal-for-a-graph/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "BFS",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/bfs-traversal-of-graph/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{ //Striver's Sheet has Course Schedule Problem's link here.
		  Problem: "Detect A cycle in Undirected Graph using BFS",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Detect A cycle in Undirected Graph using DFS",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/detect-cycle-in-an-undirected-graph/1/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Detect A cycle in a Directed Graph using DFS",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Detect A cycle in a Directed Graph using BFS",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/detect-cycle-in-a-directed-graph/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Topological Sort",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/topological-sort/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Number of islands",
		  Topic: "Graphs",
		  URL: "https://leetcode.com/problems/number-of-islands/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Bipartite Check using BFS",
		  Topic: "Graphs",
		  URL: "https://leetcode.com/problems/is-graph-bipartite/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Bipartite Check using DFS",
		  Topic: "Graphs",
		  URL: "https://leetcode.com/problems/is-graph-bipartite/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Strongly Connected Component",
		  Topic: "Graphs",
		  URL: "https://leetcode.com/problems/maximum-number-of-non-overlapping-substrings/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Dijkstra’s Algorithm",
		  Topic: "Graphs",
		  URL: "hhttps://practice.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Bellman-Ford Algorithm",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/0",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Floyd Warshall Algorithm",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/implementing-floyd-warshall2042/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "MST using Prim’s Algorithm",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "MST using Kruskal’s Algorithm",
		  Topic: "Graphs",
		  URL: "https://practice.geeksforgeeks.org/problems/minimum-spanning-tree/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   },
   {
	  topicName: "Dynamic Programming",
	  position: 0,
	  started: false,
	  doneQuestions: 0,
	  questions: [
		{
		  Problem: "Max Product Subarray",
		  Topic: "Dynamic Programming",
		  URL: "https://leetcode.com/problems/maximum-product-subarray/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Longest Increasing Subsequence",
		  Topic: "Dynamic Programming",
		  URL: "https://leetcode.com/problems/longest-increasing-subsequence/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Longest Common Subsequence",
		  Topic: "Dynamic Programming",
		  URL: "https://leetcode.com/problems/longest-common-subsequence/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "0-1 Knapsack",
		  Topic: "Dynamic Programming",
		  URL: "https://leetcode.com/problems/ones-and-zeroes/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Edit Distance",
		  Topic: "Dynamic Programming",
		  URL: "https://leetcode.com/problems/edit-distance/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Maximum sum increasing subsequence",
		  Topic: "Dynamic Programming",
		  URL: "https://practice.geeksforgeeks.org/problems/maximum-sum-increasing-subsequence4749/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		 {
		  Problem: "Matrix Chain Multiplication",
		  Topic: "Dynamic Programming",
		  URL: "https://practice.geeksforgeeks.org/problems/matrix-chain-multiplication0303/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Maximum sum path in the matrix",
		  Topic: "Dynamic Programming",
		  URL: "https://leetcode.com/problems/minimum-path-sum/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Coin change",
		  Topic: "Dynamic Programming",
		  URL: "https://leetcode.com/problems/coin-change/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Subset Sum",
		  Topic: "Dynamic Programming",
		  URL: "https://leetcode.com/problems/partition-equal-subset-sum/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Rod Cutting",
		  Topic: "Dynamic Programming",
		  URL: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Egg Dropping",
		  Topic: "Dynamic Programming",
		  URL: "https://practice.geeksforgeeks.org/problems/egg-dropping-puzzle-1587115620/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Word Break",
		  Topic: "Dynamic Programming",
		  URL: "https://practice.geeksforgeeks.org/problems/word-break1352/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Palindrome Partitioning",
		  Topic: "Dynamic Programming",
		  URL: "https://practice.geeksforgeeks.org/problems/palindromic-patitioning4845/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
		{
		  Problem: "Maximum profit in Job scheduling",
		  Topic: "Dynamic Programming",
		  URL: "https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1",
		  Done: false,
		  Bookmark: false,
		  Notes: "",
		},
	  ]
   }
  ]
export const version = 100000013;

