export default [
  {
    topicName: "Array",
    position: 0,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Two sum",
        Topic: "Array",
        URL: "https://leetcode.com/problems/two-sum/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Best Time to Buy and Sell Stock",
        Topic: "Array",
        URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Merge Sorted Array",
        Topic: "Array",
        URL: "https://leetcode.com/problems/merge-sorted-array/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Move Zeroes",
        Topic: "Array",
        URL: "https://leetcode.com/problems/move-zeroes/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Best Time to Buy and Sell Stock II",
        Topic: "Array",
        URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Running Sum of 1d Array",
        Topic: "Array",
        URL: "https://leetcode.com/problems/running-sum-of-1d-array/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Find Pivot Index",
        Topic: "Array",
        URL: "https://leetcode.com/problems/find-pivot-index/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Majority Element",
        Topic: "Array",
        URL: "https://leetcode.com/problems/majority-element/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Fibonacci Number",
        Topic: "Array",
        URL: "https://leetcode.com/problems/fibonacci-number/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Squares of a Sorted Array",
        Topic: "Array",
        URL: "https://leetcode.com/problems/squares-of-a-sorted-array/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Pascal's Triangle",
        Topic: "Array",
        URL: "https://leetcode.com/problems/pascals-triangle/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Remove Duplicates from Sorted Array",
        Topic: "Array",
        URL: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Merge Intervals",
        Topic: "Array",
        URL: "https://leetcode.com/problems/merge-intervals/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "3Sum",
        Topic: "Array",
        URL: "https://leetcode.com/problems/3sum/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Product of Array Except Self",
        Topic: "Array",
        URL: "https://leetcode.com/problems/product-of-array-except-self/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Insert Delete GetRandom O(1)",
        Topic: "Array",
        URL: "https://leetcode.com/problems/insert-delete-getrandom-o1/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Subarray Sum Equals K",
        Topic: "Array",
        URL: "https://leetcode.com/problems/subarray-sum-equals-k/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Next Permutation",
        Topic: "Array",
        URL: "https://leetcode.com/problems/next-permutation/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Spiral Matrix",
        Topic: "Array",
        URL: "https://leetcode.com/problems/spiral-matrix/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Container With Most Water",
        Topic: "Array",
        URL: "https://leetcode.com/problems/container-with-most-water/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Rotate Image",
        Topic: "Array",
        URL: "https://leetcode.com/problems/rotate-image/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Word Search",
        Topic: "Array",
        URL: "https://leetcode.com/problems/word-search/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "3Sum Closest",
        Topic: "Array",
        URL: "https://leetcode.com/problems/3sum-closest/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Game of Life",
        Topic: "Array",
        URL: "https://leetcode.com/problems/game-of-life/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Pairs of Songs With Total Durations Divisible by 60",
        Topic: "Array",
        URL: "https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "4Sum",
        Topic: "Array",
        URL: "https://leetcode.com/problems/4sum/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Find the Duplicate Number",
        Topic: "Array",
        URL: "https://leetcode.com/problems/find-the-duplicate-number/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Combination Sum",
        Topic: "Array",
        URL: "https://leetcode.com/problems/combination-sum/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Jump Game II",
        Topic: "Array",
        URL: "https://leetcode.com/problems/jump-game-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Maximum Points You Can Obtain from Cards",
        Topic: "Array",
        URL: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem:
          "Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts",
        Topic: "Array",
        URL: "https://leetcode.com/problems/maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Max Area of Island",
        Topic: "Array",
        URL: "https://leetcode.com/problems/max-area-of-island/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Find All Duplicates in an Array",
        Topic: "Array",
        URL: "https://leetcode.com/problems/find-all-duplicates-in-an-array/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "K-diff Pairs in an Array",
        Topic: "Array",
        URL: "https://leetcode.com/problems/k-diff-pairs-in-an-array/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Subsets",
        Topic: "Array",
        URL: "https://leetcode.com/problems/subsets/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Invalid Transactions",
        Topic: "Array",
        URL: "https://leetcode.com/problems/invalid-transactions/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Jump Game",
        Topic: "Array",
        URL: "https://leetcode.com/problems/jump-game/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Subarray Sums Divisible by K",
        Topic: "Array",
        URL: "https://leetcode.com/problems/subarray-sums-divisible-by-k/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "First Missing Positive",
        Topic: "Array",
        URL: "https://leetcode.com/problems/first-missing-positive/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Largest Rectangle in Histogram",
        Topic: "Array",
        URL: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Insert Delete GetRandom O(1) - Duplicates allowed",
        Topic: "Array",
        URL: "https://leetcode.com/problems/insert-delete-getrandom-o1-duplicates-allowed/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Best Time to Buy and Sell Stock III",
        Topic: "Array",
        URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Max Value of Equation",
        Topic: "Array",
        URL: "https://leetcode.com/problems/max-value-of-equation/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },
  {
    topicName: "Dynamic Programming",
    position: 1,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Maximum Subarray",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/maximum-subarray/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Climbing Stairs",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/climbing-stairs",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Divisor Game",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/divisor-game/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Counting Bits",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/counting-bits/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Decode Ways",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/decode-ways/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Word Break",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/word-break/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Delete and Earn",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/delete-and-earn/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Maximal Square",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/maximal-square/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Coin Change",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/coin-change/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Maximum Product Subarray",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/maximum-product-subarray/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Maximum Length of Repeated Subarray",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/maximum-length-of-repeated-subarray/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Palindromic Substrings",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/palindromic-substrings/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "House Robber",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/house-robber/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Continuous Subarray Sum",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/continuous-subarray-sum/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Knight Dialer",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/knight-dialer/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Longest Increasing Subsequence",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/longest-increasing-subsequence/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Unique Paths",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/unique-paths/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Count Square Submatrices with All Ones",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/count-square-submatrices-with-all-ones/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Range Sum Query 2D - Immutable",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/range-sum-query-2d-immutable/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Longest Arithmetic Subsequence",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/longest-arithmetic-subsequence/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Trapping Rain Water",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/trapping-rain-water/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Word Break II",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/word-break-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Regular Expression Matching",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/regular-expression-matching/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Maximal Rectangle",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/maximal-rectangle/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Longest Valid Parentheses",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/longest-valid-parentheses/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Edit Distance",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/edit-distance/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Difficulty of a Job Schedule",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Frog Jump",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/frog-jump/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Best Time to Buy and Sell Stock IV",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Burst Balloons",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/burst-balloons/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Cost to Merge Stones",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/minimum-cost-to-merge-stones/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Insertion Steps to Make a String Palindrome",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Super Egg Drop",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/super-egg-drop/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Count Different Palindromic Subsequences",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/count-different-palindromic-subsequences/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Cost to Cut a Stick",
        Topic: "Dynamic Programming",
        URL: "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },

  {
    topicName: "String",
    position: 2,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Add Strings",
        Topic: "String",
        URL: "https://leetcode.com/problems/add-strings/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Longest Common Prefix",
        Topic: "String",
        URL: "https://leetcode.com/problems/longest-common-prefix/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Valid Palindrome II",
        Topic: "String",
        URL: "https://leetcode.com/problems/valid-palindrome-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Roman to Integer",
        Topic: "String",
        URL: "https://leetcode.com/problems/roman-to-integer/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Implement strStr()",
        Topic: "String",
        URL: "https://leetcode.com/problems/implement-strstr/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Longest Substring Without Repeating Characters",
        Topic: "String",
        URL: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Remove to Make Valid Parentheses",
        Topic: "String",
        URL: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Longest Palindromic Substring",
        Topic: "String",
        URL: "https://leetcode.com/problems/longest-palindromic-substring/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Group Anagrams",
        Topic: "String",
        URL: "https://leetcode.com/problems/group-anagrams/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Generate Parentheses",
        Topic: "String",
        URL: "https://leetcode.com/problems/generate-parentheses/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Basic Calculator II",
        Topic: "String",
        URL: "https://leetcode.com/problems/basic-calculator-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Integer to Roman",
        Topic: "String",
        URL: "https://leetcode.com/problems/integer-to-roman/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Reverse Words in a String",
        Topic: "String",
        URL: "https://leetcode.com/problems/reverse-words-in-a-string/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Simplify Path",
        Topic: "String",
        URL: "https://leetcode.com/problems/simplify-path/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "ZigZag Conversion",
        Topic: "String",
        URL: "https://leetcode.com/problems/zigzag-conversion/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Text Justification",
        Topic: "String",
        URL: "https://leetcode.com/problems/text-justification/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Integer to English Words",
        Topic: "String",
        URL: "https://leetcode.com/problems/integer-to-english-words/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Window Substring",
        Topic: "String",
        URL: "https://leetcode.com/problems/minimum-window-substring/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Valid Number",
        Topic: "String",
        URL: "https://leetcode.com/problems/valid-number/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Distinct Subsequences",
        Topic: "String",
        URL: "https://leetcode.com/problems/distinct-subsequences/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Smallest Range Covering Elements from K Lists",
        Topic: "String",
        URL: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Substring with Concatenation of All Words",
        Topic: "String",
        URL: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },

  {
    topicName: "Maths",
    position: 3,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Reverse Integer",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/reverse-integer/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Add Binary",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/add-binary/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Palindrome Number",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/palindrome-number/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Moves to Equal Array Elements",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/minimum-moves-to-equal-array-elements/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Happy Number",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/happy-number/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Excel Sheet Column Title",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/excel-sheet-column-title/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Missing Number",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/missing-number/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Maximum Product of Three Numbers",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/maximum-product-of-three-numbers/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Power of Two",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/power-of-two/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Encode and Decode TinyURL",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/encode-and-decode-tinyurl/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "String to Integer (atoi)",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/string-to-integer-atoi/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Multiply Strings",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/multiply-strings/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Angle Between Hands of a Clock",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/angle-between-hands-of-a-clock/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Integer Break",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/integer-break/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Valid Square",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/valid-square/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "The kth Factor of n",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/the-kth-factor-of-n/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Basic Calculator",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/basic-calculator/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Max Points on a Line",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/max-points-on-a-line/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Permutation Sequence",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/permutation-sequence/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Number of Digit One",
        Topic: "MATHS",
        URL: "https://leetcode.com/problems/number-of-digit-one/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },

  {
    topicName: "Greedy",
    position: 4,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Task Scheduler",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/task-scheduler/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Gas Station",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/gas-station/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Deletion Cost to Avoid Repeating Letters",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/minimum-deletion-cost-to-avoid-repeating-letters/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Maximum Number of Events That Can Be Attended",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Deletions to Make Character Frequencies",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/minimum-deletions-to-make-character-frequencies-unique/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Remove K Digits",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/remove-k-digits/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Restore the Array From Adjacent Pairs",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/restore-the-array-from-adjacent-pairs/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Non-overlapping Intervals",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/non-overlapping-intervals/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Candy",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/candy/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Number of Taps to Open to Water a Garden",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Create Maximum Number",
        Topic: "Greedy ",
        URL: "https://leetcode.com/problems/create-maximum-number/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },

  {
    topicName: "DFS",
    position: 5,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Letter Combinations of a Phone Number",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Course Schedule II",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/course-schedule-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Decode String",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/decode-string/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Number of Provinces",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/number-of-provinces/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Clone Graph",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/clone-graph/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Shortest Bridge",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/shortest-bridge/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "All Paths From Source to Target",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/all-paths-from-source-to-target/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Surrounded Regions",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/surrounded-regions//",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "House Robber III",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/house-robber-iii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Critical Connections in a Network",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/critical-connections-in-a-network/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Remove Invalid Parentheses",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/remove-invalid-parentheses/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Longest Increasing Path in a Matrix",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Concatenated Words",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/concatenated-words/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Making A Large Island",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/making-a-large-island/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Contain Virus",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/contain-virus/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "24 Game",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/24-game/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Remove Boxes",
        Topic: "DFS",
        URL: "https://leetcode.com/problems/remove-boxes/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },
  {
    topicName: "Binary Trees",
    position: 6,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Diameter of Binary Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/diameter-of-binary-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Invert Binary Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/invert-binary-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Subtree of Another Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/subtree-of-another-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Range Sum of BST",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/range-sum-of-bst/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Symmetric Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/symmetric-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Convert Sorted Array to Binary Search Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Merge Two Binary Trees",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/merge-two-binary-trees/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Maximum Depth of Binary Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Binary Tree Paths",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/binary-tree-paths/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Same Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/same-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Lowest Common Ancestor of a Binary Search Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Path Sum",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/path-sum/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Absolute Difference in BST",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/minimum-absolute-difference-in-bst/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Sum of Left Leaves",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/sum-of-left-leaves/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Balanced Binary Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/balanced-binary-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Binary Tree Inorder Traversal",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/binary-tree-inorder-traversal/   (USING Stacks & Queues TOO)",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Count Good Nodes in Binary Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Lowest Common Ancestor of a Binary Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Binary Tree Right Side View",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/binary-tree-right-side-view/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "All Nodes Distance K in Binary Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Validate Binary Search Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/validate-binary-search-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Binary Tree Zigzag Level Order Traversal",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Binary Search Tree Iterator",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/binary-search-tree-iterator/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Binary Tree Level Order Traversal",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Path Sum III",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/path-sum-iii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Construct Binary Tree from Preorder and Postorder Traversal",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-postorder-traversal/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Unique Binary Search Trees",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/unique-binary-search-trees/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Recover Binary Search Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/recover-binary-search-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Populating Next Right Pointers in Each Node",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Flatten Binary Tree to Linked List",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Maximum Width of Binary Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/maximum-width-of-binary-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Unique Binary Search Trees II",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/unique-binary-search-trees-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Kth Smallest Element in a BST",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Redundant Connection",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/redundant-connection/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Serialize and Deserialize Binary Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Binary Tree Maximum Path Sum",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Vertical Order Traversal of a Binary Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Binary Tree Cameras",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/binary-tree-cameras/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Sum of Distances in Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/sum-of-distances-in-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Number Of Ways To Reconstruct A Tree",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/number-of-ways-to-reconstruct-a-tree/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Redundant Connection II",
        Topic: "Binary Trees",
        URL: "https://leetcode.com/problems/redundant-connection-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },
  {
    topicName: "Hash Table",
    position: 7,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Verifying an Alien Dictionary",
        Topic: "HASH TABLE",
        URL: "https://leetcode.com/problems/verifying-an-alien-dictionary/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Design Hashmap",
        Topic: "HASH TABLE",
        URL: "https://leetcode.com/problems/design-hashmap/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Top K Frequent Elements",
        Topic: "HASH TABLE",
        URL: "https://leetcode.com/problems/top-k-frequent-elements/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Design Twitter",
        Topic: "HASH TABLE",
        URL: "https://leetcode.com/problems/design-twitter/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },

  {
    topicName: "Binary Search",
    position: 8,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Square Root",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/sqrtx/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Binary Search",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/binary-search/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Count Negative Numbers in a Sorted Matrix",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Peak Index in a Mountain Array",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/peak-index-in-a-mountain-array/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Time Based Key-Value Store",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/time-based-key-value-store/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Search in rotated sorted array",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Pow(x,n)",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/powx-n/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Find First and Last Position of Element in Sorted Array",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Find peak element",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/find-peak-element/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Search a 2D matrix",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/search-a-2d-matrix/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Divide two integers",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/divide-two-integers/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Capacity To Ship Packages Within D Days",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "MInimum limit of balls in a bag",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/minimum-limit-of-balls-in-a-bag/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Median of two sorted array",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Count of Smaller Numbers After Self",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Max Sum of Rectangle No Larger Than K",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Split Array Largest sum",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/split-array-largest-sum/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Shortest Subarray with Sum at Least K",
        Topic: "BINARY SEARCH",
        URL: "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },
  {
    topicName: "BFS",
    position: 9,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Number of Islands",
        Topic: "BFS",
        URL: "https://leetcode.com/problems/number-of-islands/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Rotting oranges",
        Topic: "BFS",
        URL: "https://leetcode.com/problems/rotting-oranges/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Snakes and Ladders",
        Topic: "BFS",
        URL: "https://leetcode.com/problems/snakes-and-ladders/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Is Graph Bipartite",
        Topic: "BFS",
        URL: "https://leetcode.com/problems/is-graph-bipartite/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Jumps to reach home",
        Topic: "BFS",
        URL: "https://leetcode.com/problems/minimum-jumps-to-reach-home/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Word Ladder",
        Topic: "BFS",
        URL: "https://leetcode.com/problems/word-ladder/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Word Ladder II",
        Topic: "BFS",
        URL: "https://leetcode.com/problems/word-ladder-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Cut off trees for golf event",
        Topic: "BFS",
        URL: "https://leetcode.com/problems/cut-off-trees-for-golf-event/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Reachable Nodes In Subdivided Graph",
        Topic: "BFS",
        URL: "https://leetcode.com/problems/reachable-nodes-in-subdivided-graph/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },

  {
    topicName: "Two Pointer",
    position: 10,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Partition Labels",
        Topic: "TWO POINTER",
        URL: "https://leetcode.com/problems/partition-labels/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Sort Colours",
        Topic: "TWO POINTER",
        URL: "https://leetcode.com/problems/sort-colors/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Longest repeating character replacement",
        Topic: "TWO POINTER",
        URL: "https://leetcode.com/problems/longest-repeating-character-replacement/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Maximum number of visible points",
        Topic: "TWO POINTER",
        URL: "https://leetcode.com/problems/maximum-number-of-visible-points/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Subarray with K different integers",
        Topic: "TWO POINTER",
        URL: "https://leetcode.com/problems/subarrays-with-k-different-integers/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },
  {
    topicName: "BackTracking",
    position: 11,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Palindrome Partitioning",
        Topic: "BackTracking",
        URL: "https://leetcode.com/problems/palindrome-partitioning/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Combining sum II",
        Topic: "BackTracking",
        URL: "https://leetcode.com/problems/combination-sum-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Combination",
        Topic: "BackTracking",
        URL: "https://leetcode.com/problems/combinations/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Permutation II",
        Topic: "BackTracking",
        URL: "https://leetcode.com/problems/permutations-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Subset II",
        Topic: "BackTracking",
        URL: "https://leetcode.com/problems/subsets-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Beautiful Arrangement",
        Topic: "BackTracking",
        URL: "https://leetcode.com/problems/beautiful-arrangement/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: " Subsets",
        Topic: "BackTracking",
        URL: "https://leetcode.com/problems/word-search-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Sudoku Solver",
        Topic: "BackTracking",
        URL: "https://leetcode.com/problems/sudoku-solver/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "N-Queens",
        Topic: "BackTracking",
        URL: "https://leetcode.com/problems/n-queens/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Unique Paths III",
        Topic: "BackTracking",
        URL: "https://leetcode.com/problems/unique-paths-iii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },

  {
    topicName: "Stacks & Queues",
    position: 12,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Min Stack",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/min-stack/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Next Greater Element I",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/next-greater-element-i/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Backspace string compare",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/backspace-string-compare/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Implement queue using stack",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/implement-queue-using-stacks/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Implement stack using queue",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/implement-stack-using-queues/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Remove stack using queue",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Daily temperatures",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/daily-temperatures/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Flatten Nested List Iterator",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/flatten-nested-list-iterator/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Online Stock Span",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/online-stock-span/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Cost Tree From Leaf Values",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Sum of Subarray Minimums",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/sum-of-subarray-minimums/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Evaluate Reverse Polish Notation",
        Topic: "Stacks & Queues",
        URL: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },

  {
    topicName: "Design",
    position: 13,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "LRU Cache",
        Topic: "DESIGN",
        URL: "https://leetcode.com/problems/lru-cache/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Find Median from Data Stream",
        Topic: "DESIGN",
        URL: "https://leetcode.com/problems/find-median-from-data-stream/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Design Underground System",
        Topic: "DESIGN",
        URL: "https://leetcode.com/problems/design-underground-system/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "LFU Cache",
        Topic: "DESIGN",
        URL: "https://leetcode.com/problems/lfu-cache/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Tweet Counts Per Frequency\r",
        Topic: "DESIGN",
        URL: "https://leetcode.com/problems/tweet-counts-per-frequency/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "All O`one Data Structure",
        Topic: "DESIGN",
        URL: "https://leetcode.com/problems/all-oone-data-structure/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Design Browser History",
        Topic: "DESIGN",
        URL: "https://leetcode.com/problems/design-browser-history/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },

  {
    topicName: "Graph",
    position: 14,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Employee Importance",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/employee-importance/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Find the Town Judge",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/find-the-town-judge/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Evaluate Division",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/evaluate-division/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Accounts Merge",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/accounts-merge/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Network Delay Time",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/network-delay-time/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Find Eventual Safe States",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/find-eventual-safe-states/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Keys And Rooms",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/keys-and-rooms/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Possible Bipartiton",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/possible-bipartition/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Most Stones Removed with Same Row or Column",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Regions cut by slashes",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/regions-cut-by-slashes/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Satisfiability of Equality Equations",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/satisfiability-of-equality-equations/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "As Far from Land as Possible",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/as-far-from-land-as-possible/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Number of Closed Islands",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/number-of-closed-islands/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Number of Operations to Make Network Connected",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/number-of-operations-to-make-network-connected/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem:
          "Find the City With the Smallest Number of Neighbors at a Threshold Distance",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Time Needed to Inform All Employees",
        Topic: "Graph",
        URL: "https://leetcode.com/problems/time-needed-to-inform-all-employees/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },

  {
    topicName: "Linked List",
    position: 15,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Delete Node in a Linked List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/delete-node-in-a-linked-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Middle of the Linked List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/middle-of-the-linked-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Convert Binary Number in a Linked List to Integer",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: " Design HashSet",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/design-hashset/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Design Hashmap",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/design-hashmap/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Reverse Linked List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/reverse-linked-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Merge Two Sorted Lists",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/merge-two-sorted-lists/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Remove Duplicates from Sorted List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Intersection of Two Linked Lists",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/intersection-of-two-linked-lists/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Linked List cycle",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/linked-list-cycle/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Palindrome Linked List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/palindrome-linked-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Remove Linked List elements",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/remove-linked-list-elements/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Add two numbers",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/add-two-numbers/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Copy list with random pointer",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/copy-list-with-random-pointer/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Add two numbers II",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/add-two-numbers-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Reverse Linked List ",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/reverse-linked-list-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Recorder List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/reorder-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Remove Nth Node From End of List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: " Flatten a Multilevel Doubly Linked List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Partition List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/partition-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Remove Duplicates from Sorted List II",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Odd Even Linked List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/odd-even-linked-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Sort List",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/sort-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Swap Nodes in Pairs",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/swap-nodes-in-pairs/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Rotate list",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/rotate-list/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Merge k Sorted Lists",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/merge-k-sorted-lists/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Reverse Nodes in k-Group",
        Topic: "Linked List",
        URL: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },
  {
    topicName: "Heap",
    position: 16,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "K Closest Points to Origin",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/k-closest-points-to-origin/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Kth Largest Element in an Array",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Reorganize string",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/reorganize-string/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Furthest Building You Can Reach",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/furthest-building-you-can-reach/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: " Kth Smallest Element in a Sorted Matrix",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Cheapest Flights Within K Stops",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Find the Most Competitive Subsequence",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/find-the-most-competitive-subsequence/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Ugly Number II",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/ugly-number-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Merge k Sorted Lists",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/merge-k-sorted-lists/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Sliding Window Maximum",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/sliding-window-maximum/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "The Skyline Problem",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/the-skyline-problem/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Trapping Rain Water II",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/trapping-rain-water-ii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Number of Refueling Stops",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/minimum-number-of-refueling-stops/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Swim in Rising Water",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/swim-in-rising-water/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Shortest Path to Get All Keys",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/shortest-path-to-get-all-keys/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Minimum Cost to Hire K Workers",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/minimum-cost-to-hire-k-workers/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "K-th Smallest Prime Fraction",
        Topic: "Heap",
        URL: "https://leetcode.com/problems/k-th-smallest-prime-fraction/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },
  {
    topicName: "Sliding Window",
    position: 17,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Problem: "Longest Substring with At Least K Repeating Characters",
        Topic: "Sliding Window",
        URL: "https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: " Max Consecutive Ones III",
        Topic: "Sliding Window",
        URL: "https://leetcode.com/problems/max-consecutive-ones-iii/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Grumpy Bookstore Owner",
        Topic: "Sliding Window",
        URL: "https://leetcode.com/problems/grumpy-bookstore-owner/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
      {
        Problem: "Sliding Window Median",
        Topic: "Sliding Window",
        URL: "https://leetcode.com/problems/sliding-window-median/",
        Done: false,
        Bookmark: false,
        Notes: "",
      },
    ],
  },
];
export const version = 100000013;
